dist: xenial
sudo: required
language: node_js
node_js:
  - "12"
os:
  - linux
addons:
  chrome: stable
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
services:
  - xvfb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - google-chrome-stable --version
install:
  - yarn --frozen-lockfile
script:
  - yarn run lint
  - yarn run test -- --watch=false
  - yarn run pree2e
  - yarn run e2e
notifications:
  email: false
cache: yarn
