dist: trusty
sudo: required
language: node_js
node_js:
  - "12"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - sh -e /etc/init.d/xvfb start
  - yarn global add @angular/cli
install:
  - yarn --frozen-lockfile
script:
  - yarn run lint
  - yarn run test -- --watch=false
  - yarn run pree2e
  - yarn run e2e
notifications:
  email: false
cache: yarn
