dist: xenial
sudo: required
language: node_js
node_js:
  - "12"
os:
  - linux
addons:
  chrome: stable
services:
  - xvfb
before_install:
  - google-chrome-stable --version
install:
  - yarn --frozen-lockfile
script:
  - yarn run lint
  - yarn run test --watch=false
  - yarn run pree2e
  - yarn run e2e
notifications:
  email: false
cache: yarn
